CREATE DATABASE IF NOT EXISTS supermarket;

USE supermarket;

CREATE TABLE IF NOT EXISTS user(
id INT AUTO_INCREMENT NOT NULL,
userName VARCHAR (100) NOT NULL,
password VARCHAR (100) NOT NULL,
fullName VARCHAR (100) NOT NULL,
email VARCHAR (100) NOT NULL,
balance float,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS admin (
id INT AUTO_INCREMENT NOT NULL,
userName VARCHAR (100) NOT NULL,
fullName VARCHAR (100) NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS product (
id INT AUTO_INCREMENT NOT NULL,
productName VARCHAR (50) NOT NULL,
weight FLOAT NOT NULL,
info VARCHAR (10000) NOT NULL,
price FLOAT NOT NULL,
quantity int,
purchasePrice FLOAT NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
PRIMARY KEY (id)
);

SELECT * FROM product;

ALTER TABLE admin ADD password VARCHAR (100) NOT NULL;

ALTER TABLE product MODIFY purchasePrice FLOAT NOT NULL;

INSERT INTO admin (userName, password, fullName) VALUES ('admin', 'password', 'Lubova Streluhina');


DROP TABLE cart;

CREATE TABLE IF NOT EXISTS cart (
id INT AUTO_INCREMENT NOT NULL,
productName VARCHAR (50) NOT NULL,
weight FLOAT NOT NULL,
info VARCHAR (10000) NOT NULL,
price FLOAT NOT NULL,
quantity int,
userID INT NOT NULL,
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
FOREIGN KEY (userID) REFERENCES user(id),
PRIMARY KEY (id)
);

SELECT * FROM cart;

CREATE TABLE IF NOT EXISTS dailyInventory (
	id INT AUTO_INCREMENT NOT NULL,
    productID INT NOT NULL,
    date DATE NOT NULL,
    startQuantity INT NOT NULL,
    endQuantity INT NOT NULL,
    price FLOAT NOT NULL,
    purchasePrice FLOAT NOT NULL,
    FOREIGN KEY(productID) REFERENCES product(id),
    PRIMARY KEY(id, date, productID)
);

SELECT * FROM dailyInventory;

DROP TABLE dailyInventory;

UPDATE dailyInventory SET endQuantity = quantity FROM product WHERE dailyInventory.productID = p.id AND dailyInventory.date = 2023-04-12;